# permissions for end users to view configurationproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configurationprovider-viewer-role
rules:
- apiGroups:
  - appconfig.kubernetes.config
  resources:
  - configurationproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appconfig.kubernetes.config
  resources:
  - configurationproviders/status
  verbs:
  - get
